<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_metadata_display_menu() {
  return array(
    'admin/islandora/islandora_metadata_display' => array(
      'title' => 'Metadata Display',
      'description' => 'GUI for edting metadata display',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_metadata_display_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/object/%islandora_object/metadata' => array(
      'title' => 'Metadata',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_metadata_display_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_metsdata_display_view_access',
      'access arguments' => array(2),
      'weight' => 1,
    )
  );
}

function islandora_metsdata_display_view_access($object) {
  return islandora_metadata_display_conf($object);
}

function islandora_metadata_display_conf($object) {
  $data = data();
  $models = array_flip($object->models);
  $conf = array_intersect_key($data, $models);
  if (count($conf) >= 1) {
    return array_shift($conf);
  }
  return FALSE;
}

function islandora_metadata_display_build($data, $xml) {
  $rows = array();

      foreach ($data as $line) {
        //dsm($line, 'line');
        try {
          dd($xml, 'xml');
          $values = $xml->xpath($line['path']);
          $label = $line['label'];
          foreach ($values as $value) {
            if(isset($line['data'])) {
              dsm($value, 'value');
              $value = islandora_metadata_display_build($line['data'], $value);
            }
            $value = (string) $value;
            if ($value) {
              if (isset($line['link']) && $line['link']) {
                $line['link'] = preg_replace('/%value%/', $value, $line['link']);
                $value = l($value, $line['link']);
              }

              $rows[] = array(
                $label,
                $value,
              );
              $label = '';
            }

            if ((isset($line['multi_value']) && !$line['multi_value']) || !isset($line['multi_value'])) {
              break;
            }
        }
      } catch (Exception $exc) {

      }
    }


  return theme_table(array(
        'header' => array('label', 'value'),
        'rows' => $rows,
        'attributes' => array(),
        'empty' => t('No metadata found'),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => TRUE,
      ));
}


function islandora_metadata_display_view($object) {

  $conf = islandora_metadata_display_conf($object);
  if (isset($conf)) {
    $data = $conf['data'];
    $table = '';
    try {
      $xml = (isset($object[$conf['ds_id']]) ? $object[$conf['ds_id']]->content : NULL);
      dsm($xml, 'xml');
      $metadata = new SimpleXMLElement($xml);
      $metadata->registerXPathNamespace($conf['namespace']['ns'], $conf['namespace']['uri']);
      $table = islandora_metadata_display_build($data, $metadata);

    } catch (Exception $exc) {
      //catch error if need be
    }
  }
  return $table;
}

//move this stuff to a db table
function data() {
  $data = array(
    'islandora:sp_basic_image' => array(
      'ds_id' => 'MODS',
      'namespace' => array(
        'ns' => 'mods',
        'uri' => 'http://www.loc.gov/mods/v3',
      ),
      'data' => array(
        array(
          'label' => 'Place',
          'link' => 'http://google.ca/%value%',
          'path' => '//mods:place',
          'multi_value' => TRUE,
          'data' => array(
            'label' => 'Place',
            'link' => 'http://google.ca/%value%',
            'path' => 'mods:placeTerm',
            'multi_value' => TRUE,
          ),
        ),
      ),
    ),
    'islandora:sp_large_image_cmodel' => array(
      'ds_id' => 'MODS',
      'namespace' => array(
        'ns' => 'mods',
        'uri' => 'http://www.loc.gov/mods/v3',
      ),
      'data' => array(
        array(
          'label' => 'Titlee',
          'link' => 'http://google.ca/%value%',
          'path' => '//mods:name',
        ),
      ),
    ),
  );
  return $data;
}

/**
 * Implements hook_theme().
 */
function islandora_metadata_display_theme() {


  return array(
  );
}

function islandora_metadata_display_islandora_view_object_alter(&$object, &$rendered) {
  //dsm($rendered, 'rendered');
}