<?php

/**
 * @file
 * Defines the install/uninstall hooks for this module.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_metadata_display_uninstall() {
  $variables = array();
  // Delete the Drupal variables defined by this module.
  array_walk($variables, 'variable_del');
}

/*
function islandora_metadata_display_schema() {
  $schema['islandora_metadata_display'] = array();

  return $schema;
}
 *
 */